### ISSUE TITLE
Left right channels are unbalanced after a while

### ISSUE THREAD

**Issue by idelsink** [garrett92895/gnome-volume-step-osd#2]
I have bound this script to my volume dial.
After a while the left and right balance is all over the place.

## Left right balance changed

Before:
```bash
$ amixer get Master
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 10486 [16%] [on]
  Front Right: Playback 10486 [16%] [on]
```
After:
```
$ amixer get Master
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 3476 [5%] [on]
  Front Right: Playback 4582 [7%] [on]
```

I tested this with a small script that calls `volume-change.py` multiple times from detached subshells.

```bash
#!/usr/bin/env bash

# Small test script to call the python script multiple times
for run in {1..100}; do
    (./volume-change.py increase 1)&
    usleep 1000
    (./volume-change.py decrease 1)&
    usleep 1000
done

amixer get Master
echo "Are the left and right channel the same?"
wait
```
This is the same as if I would spam my volume dial like I normally do.

After the run, the left and right channels are borked. The only thing I can think of is that before the first call to `amixer` is done, another one starts. This is understandable when no mutex is used.

For this reason the script should first find the current volume, add or subtract the value and *then* apply the volume without a delta as is done in here:
https://github.com/garrett92895/gnome-volume-step-osd/blob/ffa7f32fa4c24c38de79d7d5604b693f2f2e4155/volume-change.py#L28-L31

## Summary

Left and right channel balance is borked after a while. The solution would be to not work with delta's which could increase the errors but work with absolute values.

**Comment by Ortega-Dan** [comment]
It looks like PR #3 solved this issue, I'm just adding a comment to recommend this issue to be closed.

**Comment by idelsink** [comment]
Closed because issue is resolved :+1:
